#ifndef GUARD_ITEM_H
#define GUARD_ITEM_H
#include "gba/types.h"
#include "constants/items.h"
#include "constants/tms_hms.h"
#define ITEM_COUNT 377
/* Named TM aliases (generated by preproc in GBA build) */
#define ITEM_TM_FOCUS_PUNCH  ITEM_TM01
#define ITEM_TM_EARTHQUAKE   ITEM_TM26
#define ITEM_TM_REST         ITEM_TM44
struct Item { u8 name[14]; u16 itemId; u16 price; u8 description[128]; u8 mystery1; u8 mystery2; u8 pocket; u8 type; void *fieldUseFunc; u8 battleUsage; void *battleUseFunc; u8 secondary; u8 registrability; };
extern const struct Item gItems[];
static inline u16 GetItemEffect(u16 itemId) { return 0; }
static inline u8 ItemId_GetHoldEffect(u16 itemId) { return 0; }
static inline u8 ItemId_GetHoldEffectParam(u16 itemId) { return 0; }
static inline u8 ItemId_GetPocket(u16 itemId) { return 0; }
static inline u8 ItemId_GetType(u16 itemId) { return 0; }
static inline u16 ItemId_GetPrice(u16 itemId) { return 0; }
static inline u8 ItemId_GetBattleUsage(u16 itemId) { return 0; }
static inline u8 ItemId_GetFieldUseFunc(u16 itemId) { return 0; }
static inline const u8 *ItemId_GetName(u16 itemId);
static inline u8 ItemId_GetSecondaryId(u16 itemId) { return 0; }
static inline const u8 *ItemId_GetDescription(u16 itemId) { return NULL; }
#endif
