#!/usr/bin/env python3
"""gen_item_hold_effects.py — Generate holdEffect/holdEffectParam/name lookup tables.

Reads include/constants/hold_effects.h, include/constants/items.h, and
src/data/items.h and emits:
  battle_desktop/generated/item_hold_effects.c   — lookup arrays indexed by item ID
  battle_desktop/generated/item_hold_effects.h   — extern declarations

Run from the root of the pokeemerald repository:
    python3 battle_desktop/tools/gen_item_hold_effects.py
"""

import re
import os
import sys


def parse_defines(path, prefix=''):
    """Return {NAME: int_value} for all matching #define lines."""
    result = {}
    pattern = re.compile(r'^\s*#define\s+(\w+)\s+(\d+)')
    with open(path, 'r') as f:
        for line in f:
            m = pattern.match(line)
            if m and (not prefix or m.group(1).startswith(prefix)):
                result[m.group(1)] = int(m.group(2))
    return result


def parse_items_data(path, item_ids, hold_effect_ids):
    """
    Parse src/data/items.h and return three dicts:
      hold_effects[item_id]       = hold_effect value (int)
      hold_effect_params[item_id] = hold_effect_param value (int)
      item_names[item_id]         = item name string (ASCII)
    Uses designated-initializer structure: [ITEM_X] = { ... }
    """
    hold_effects = {}
    hold_effect_params = {}
    item_names = {}

    with open(path, 'r') as f:
        content = f.read()

    # Find each [ITEM_X] = { ... } block.
    # We scan for "[ITEM_NAME] =" followed by a brace block.
    # Since braces can be nested in complex cases, use a simple scan.
    i = 0
    n = len(content)
    item_block_re = re.compile(r'\[\s*(ITEM_\w+)\s*\]\s*=\s*\{')

    while i < n:
        m = item_block_re.search(content, i)
        if not m:
            break

        item_name = m.group(1)
        item_id   = item_ids.get(item_name)
        brace_start = m.end() - 1  # points at '{'

        # Find matching '}'
        depth = 0
        j = brace_start
        while j < n:
            if content[j] == '{':
                depth += 1
            elif content[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        block = content[brace_start:j+1]

        if item_id is not None:
            # Extract .holdEffect = HOLD_EFFECT_XXX
            he_m = re.search(r'\.holdEffect\s*=\s*(HOLD_EFFECT_\w+|\d+)', block)
            if he_m:
                val_str = he_m.group(1)
                val = hold_effect_ids.get(val_str, None)
                if val is None:
                    try:
                        val = int(val_str)
                    except ValueError:
                        val = 0
                hold_effects[item_id] = val

            # Extract .holdEffectParam = N
            hp_m = re.search(r'\.holdEffectParam\s*=\s*(\d+)', block)
            if hp_m:
                hold_effect_params[item_id] = int(hp_m.group(1))

            # Extract .name = _("...") or .name = __("...")
            name_m = re.search(r'\.name\s*=\s*_+\(\s*"([^"]+)"\s*\)', block)
            if name_m:
                item_names[item_id] = name_m.group(1)

        i = j + 1

    return hold_effects, hold_effect_params, item_names


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root  = os.path.join(script_dir, '..', '..')
    out_dir    = os.path.join(script_dir, '..', 'generated')
    os.makedirs(out_dir, exist_ok=True)

    hold_effects_h = os.path.join(repo_root, 'include', 'constants', 'hold_effects.h')
    items_const_h  = os.path.join(repo_root, 'include', 'constants', 'items.h')
    items_data_h   = os.path.join(repo_root, 'src',     'data',      'items.h')

    item_ids       = parse_defines(items_const_h,  'ITEM_')
    hold_effect_ids = parse_defines(hold_effects_h, 'HOLD_EFFECT_')

    items_count = item_ids.get('ITEMS_COUNT', max(item_ids.values()) + 1)

    hold_effects, hold_effect_params, item_names = parse_items_data(
        items_data_h, item_ids, hold_effect_ids)

    print(f'Parsed {len(hold_effects)} items with holdEffect, '
          f'{len(hold_effect_params)} with holdEffectParam, '
          f'{len(item_names)} with name. '
          f'ITEMS_COUNT={items_count}')

    # Build flat arrays
    he_arr  = [hold_effects.get(i,      0) for i in range(items_count)]
    hep_arr = [hold_effect_params.get(i, 0) for i in range(items_count)]

    # Build name array (NULL for items with no name)
    name_arr = [item_names.get(i) for i in range(items_count)]

    # --- item_hold_effects.h ---
    h_path = os.path.join(out_dir, 'item_hold_effects.h')
    with open(h_path, 'w') as f:
        f.write('/* Auto-generated by gen_item_hold_effects.py — do not edit. */\n')
        f.write('#ifndef GUARD_BATTLE_DESKTOP_ITEM_HOLD_EFFECTS_H\n')
        f.write('#define GUARD_BATTLE_DESKTOP_ITEM_HOLD_EFFECTS_H\n\n')
        f.write('#include "gba/types.h"\n\n')
        f.write(f'#define DESKTOP_ITEMS_COUNT {items_count}\n\n')
        f.write('extern const u8 gDesktopItemHoldEffects[];\n')
        f.write('extern const u8 gDesktopItemHoldEffectParams[];\n')
        f.write('extern const char * const gDesktopItemNames[];\n\n')
        f.write('#endif /* GUARD_BATTLE_DESKTOP_ITEM_HOLD_EFFECTS_H */\n')

    # --- item_hold_effects.c ---
    c_path = os.path.join(out_dir, 'item_hold_effects.c')
    with open(c_path, 'w') as f:
        f.write('/* Auto-generated by gen_item_hold_effects.py — do not edit. */\n')
        f.write('#include "battle_desktop/generated/item_hold_effects.h"\n\n')

        f.write(f'const u8 gDesktopItemHoldEffects[{items_count}] = {{\n')
        for i, v in enumerate(he_arr):
            f.write(f'    /* {i:3d} */ {v},\n')
        f.write('};\n\n')

        f.write(f'const u8 gDesktopItemHoldEffectParams[{items_count}] = {{\n')
        for i, v in enumerate(hep_arr):
            f.write(f'    /* {i:3d} */ {v},\n')
        f.write('};\n\n')

        f.write(f'const char * const gDesktopItemNames[{items_count}] = {{\n')
        for i, name in enumerate(name_arr):
            if name is not None:
                # Escape any backslashes/quotes in the name
                escaped = name.replace('\\', '\\\\').replace('"', '\\"')
                f.write(f'    /* {i:3d} */ "{escaped}",\n')
            else:
                f.write(f'    /* {i:3d} */ NULL,\n')
        f.write('};\n')

    print(f'Written: {h_path}')
    print(f'Written: {c_path}')


if __name__ == '__main__':
    main()
