#!/usr/bin/env python3
"""gen_name_tables.py — Generate C name-to-ID lookup tables from constants headers.

Reads include/constants/species.h, moves.h, and items.h and emits:
  battle_desktop/generated/name_tables.c   — lookup arrays
  battle_desktop/generated/name_tables.h   — extern declarations

Run from the root of the pokeemerald repository:
    python3 battle_desktop/tools/gen_name_tables.py
"""

import re
import os
import sys


def parse_defines(path, prefix):
    """Return list of (NAME, int_value) pairs for #define PREFIX_NAME N lines."""
    entries = []
    pattern = re.compile(r'^\s*#define\s+' + re.escape(prefix) + r'(\w+)\s+(\d+)')
    with open(path, 'r') as f:
        for line in f:
            m = pattern.match(line)
            if m:
                name = m.group(1)
                value = int(m.group(2))
                entries.append((name, value))
    return entries


def emit_table(f, c_type, table_name, count_name, entries):
    f.write(f'const {c_type} {table_name}[] = {{\n')
    for name, value in entries:
        escaped = name.replace('"', '\\"')
        f.write(f'    {{"{escaped}", {value}}},\n')
    f.write('};\n')
    f.write(f'const int {count_name} = {len(entries)};\n\n')


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.join(script_dir, '..', '..')
    out_dir = os.path.join(script_dir, '..', 'generated')
    os.makedirs(out_dir, exist_ok=True)

    species_h = os.path.join(repo_root, 'include', 'constants', 'species.h')
    moves_h   = os.path.join(repo_root, 'include', 'constants', 'moves.h')
    items_h   = os.path.join(repo_root, 'include', 'constants', 'items.h')

    species = parse_defines(species_h, 'SPECIES_')
    moves   = parse_defines(moves_h,   'MOVE_')
    items   = parse_defines(items_h,   'ITEM_')

    if not species:
        print(f'ERROR: no SPECIES_ defines found in {species_h}', file=sys.stderr)
        sys.exit(1)
    if not moves:
        print(f'ERROR: no MOVE_ defines found in {moves_h}', file=sys.stderr)
        sys.exit(1)
    if not items:
        print(f'ERROR: no ITEM_ defines found in {items_h}', file=sys.stderr)
        sys.exit(1)

    print(f'Found {len(species)} species, {len(moves)} moves, {len(items)} items.')

    # --- name_tables.h ---
    h_path = os.path.join(out_dir, 'name_tables.h')
    with open(h_path, 'w') as f:
        f.write('/* Auto-generated by gen_name_tables.py — do not edit. */\n')
        f.write('#ifndef GUARD_BATTLE_DESKTOP_NAME_TABLES_H\n')
        f.write('#define GUARD_BATTLE_DESKTOP_NAME_TABLES_H\n\n')
        f.write('#include "gba/types.h"\n\n')
        f.write('typedef struct { const char *name; u16 id; } NameIdPair;\n\n')
        f.write('extern const NameIdPair gSpeciesNamesTable[];\n')
        f.write('extern const int        gSpeciesNamesCount;\n\n')
        f.write('extern const NameIdPair gMoveNamesTable[];\n')
        f.write('extern const int        gMoveNamesCount;\n\n')
        f.write('extern const NameIdPair gItemNamesTable[];\n')
        f.write('extern const int        gItemNamesCount;\n\n')
        f.write('#endif /* GUARD_BATTLE_DESKTOP_NAME_TABLES_H */\n')

    # --- name_tables.c ---
    c_path = os.path.join(out_dir, 'name_tables.c')
    with open(c_path, 'w') as f:
        f.write('/* Auto-generated by gen_name_tables.py — do not edit. */\n')
        f.write('#include "battle_desktop/generated/name_tables.h"\n\n')
        emit_table(f, 'NameIdPair', 'gSpeciesNamesTable', 'gSpeciesNamesCount', species)
        emit_table(f, 'NameIdPair', 'gMoveNamesTable',    'gMoveNamesCount',    moves)
        emit_table(f, 'NameIdPair', 'gItemNamesTable',    'gItemNamesCount',    items)

    print(f'Written: {h_path}')
    print(f'Written: {c_path}')


if __name__ == '__main__':
    main()
