"""Featurized observation wrapper for Pokémon battle environments.

Replaces opaque integer IDs (species, moves, abilities) with meaningful
numerical features that a neural network can learn from:

- Move features: power, accuracy, type one-hot, physical/special/status,
  STAB bonus, type effectiveness vs opponent, PP fraction
- Active mon features: HP fraction, stat stages (normalised), types one-hot,
  status flags
- Party features: HP fractions, alive counts
- Field features: weather, side conditions, spikes

All values are normalised to approximately [0, 1] or [-1, 1].
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import gymnasium as gym
import numpy as np
from gymnasium import spaces

from pokeemerald_battle._ffi import (
    BATTLE_MAX_BATTLERS,
    BATTLE_MAX_MOVES,
    BATTLE_NUM_SIDES,
    BATTLE_PARTY_SIZE,
)

# ---------------------------------------------------------------------------
# Game data constants
# ---------------------------------------------------------------------------

NUM_TYPES = 18  # Normal(0) through Dark(17); Mystery(9) treated as Normal

# Gen 3 physical/special split is by type, not by move
PHYSICAL_TYPES = {0, 1, 2, 3, 4, 5, 6, 7, 8}  # Normal..Steel
SPECIAL_TYPES = {10, 11, 12, 13, 14, 15, 16, 17}  # Fire..Dark

# Type effectiveness chart: effectiveness[atk_type][def_type] = multiplier
# Default is 1.0 (neutral). Built from the game's gTypeEffectiveness table.
_EFFECTIVENESS: dict[int, dict[int, float]] = {}


def _build_type_chart() -> None:
    """Build type effectiveness lookup from game data."""
    if _EFFECTIVENESS:
        return  # already built

    # Triples from gTypeEffectiveness in src/battle_main.c
    # (attacking_type, defending_type, multiplier)
    # multiplier: 20=super effective (2x), 5=not effective (0.5x), 0=immune
    triples = [
        (0, 5, 0.5), (0, 8, 0.5), (0, 7, 0.0),
        (10, 10, 0.5), (10, 11, 0.5), (10, 12, 2.0), (10, 15, 2.0),
        (10, 6, 2.0), (10, 5, 0.5), (10, 16, 0.5), (10, 8, 2.0),
        (11, 10, 2.0), (11, 11, 0.5), (11, 12, 0.5), (11, 4, 2.0), (11, 5, 2.0), (11, 16, 0.5),
        (13, 11, 2.0), (13, 13, 0.5), (13, 12, 0.5), (13, 4, 0.0), (13, 2, 2.0), (13, 16, 0.5),
        (12, 10, 0.5), (12, 11, 2.0), (12, 12, 0.5), (12, 3, 0.5),
        (12, 4, 2.0), (12, 2, 0.5), (12, 6, 0.5), (12, 5, 2.0), (12, 16, 0.5), (12, 8, 0.5),
        (15, 11, 0.5), (15, 12, 2.0), (15, 15, 0.5), (15, 4, 2.0),
        (15, 2, 2.0), (15, 16, 2.0), (15, 8, 0.5), (15, 10, 0.5),
        (1, 0, 2.0), (1, 15, 2.0), (1, 3, 0.5), (1, 2, 0.5),
        (1, 14, 0.5), (1, 6, 0.5), (1, 5, 2.0), (1, 17, 2.0),
        (1, 8, 2.0), (1, 7, 0.0),
        (3, 12, 2.0), (3, 3, 0.5), (3, 4, 0.5), (3, 5, 0.5), (3, 7, 0.5), (3, 8, 0.0),
        (4, 10, 2.0), (4, 13, 2.0), (4, 12, 0.5), (4, 3, 2.0),
        (4, 2, 0.0), (4, 6, 0.5), (4, 5, 2.0), (4, 8, 2.0),
        (2, 13, 0.5), (2, 12, 2.0), (2, 1, 2.0), (2, 6, 2.0), (2, 5, 0.5), (2, 8, 0.5),
        (14, 1, 2.0), (14, 3, 2.0), (14, 14, 0.5), (14, 17, 0.0), (14, 8, 0.5),
        (6, 10, 0.5), (6, 12, 2.0), (6, 1, 0.5), (6, 3, 0.5),
        (6, 2, 0.5), (6, 14, 2.0), (6, 7, 0.5), (6, 17, 2.0), (6, 8, 0.5),
        (5, 10, 2.0), (5, 15, 2.0), (5, 1, 0.5), (5, 4, 0.5),
        (5, 2, 2.0), (5, 6, 2.0), (5, 8, 0.5),
        (7, 0, 0.0), (7, 14, 2.0), (7, 17, 0.5), (7, 8, 0.5), (7, 7, 2.0),
        (16, 16, 2.0), (16, 8, 0.5),
        (17, 1, 0.5), (17, 14, 2.0), (17, 7, 2.0), (17, 17, 0.5), (17, 8, 0.5),
        (8, 10, 0.5), (8, 11, 0.5), (8, 13, 0.5), (8, 15, 2.0), (8, 5, 2.0), (8, 8, 0.5),
    ]
    for atk_t, def_t, mult in triples:
        _EFFECTIVENESS.setdefault(atk_t, {})[def_t] = mult


def type_effectiveness(atk_type: int, def_type1: int, def_type2: int) -> float:
    """Compute combined type effectiveness multiplier."""
    _build_type_chart()
    m1 = _EFFECTIVENESS.get(atk_type, {}).get(def_type1, 1.0)
    m2 = _EFFECTIVENESS.get(atk_type, {}).get(def_type2, 1.0) if def_type2 != def_type1 else 1.0
    return m1 * m2


# ---------------------------------------------------------------------------
# Move database (loaded from JSON generated by tools/parse_moves.py)
# ---------------------------------------------------------------------------

_MOVE_DB: dict[int, dict] = {}


def _load_move_db() -> None:
    if _MOVE_DB:
        return
    db_path = Path(__file__).parent / "move_data.json"
    with open(db_path) as f:
        raw = json.load(f)
    for k, v in raw.items():
        _MOVE_DB[int(k)] = v


def get_move_info(move_id: int) -> dict:
    """Return move data dict or a zero-power stub for MOVE_NONE."""
    _load_move_db()
    return _MOVE_DB.get(move_id, {"power": 0, "type": 0, "accuracy": 0, "priority": 0, "pp": 0})


# ---------------------------------------------------------------------------
# Feature sizes
# ---------------------------------------------------------------------------

# Per-move features (agent): power(1) + accuracy(1) + priority(1) + type_onehot(18)
#   + category(3: phys/spec/status) + STAB(1) + effectiveness(1) + pp_frac(1)
#   + damage_frac(1)  ← estimated damage as fraction of opponent HP
MOVE_FEAT_SIZE = 1 + 1 + 1 + NUM_TYPES + 3 + 1 + 1 + 1 + 1  # = 28

# Per-move features (opponent): power(1) + accuracy(1) + priority(1)
#   + category(3) + STAB(1) + effectiveness_vs_agent(1) + damage_frac(1)
OPP_MOVE_FEAT_SIZE = 1 + 1 + 1 + 3 + 1 + 1 + 1  # = 9

# Per-active-mon features (agent's + opponent's):
#   hp_frac(1) + types_onehot(18) + stat_stages(5 combat stats normalised)
#   + status_flags(6: sleep, poison, burn, freeze, paralyse, toxic) + level(1)
MON_FEAT_SIZE = 1 + NUM_TYPES + 5 + 6 + 1  # = 31

# Tactical features: speed_advantage(1) + agent_can_ko(1) + opp_can_ko(1)
TACTICAL_FEAT_SIZE = 3

# Per-bench-mon features (agent): hp_frac(1) + defensive_matchup(1)
#   + best_move_effectiveness(1) + status_any(1) + is_alive(1)
BENCH_MON_FEAT_SIZE = 5
NUM_BENCH_SLOTS = BATTLE_PARTY_SIZE - 1  # 5 (exclude active)

# Per-bench-mon features (opponent): hp_frac(1) + is_alive(1)
OPP_BENCH_MON_FEAT_SIZE = 2

# Agent's moves: 4 * MOVE_FEAT_SIZE = 112
# Opponent's moves: 4 * OPP_MOVE_FEAT_SIZE = 36
# Agent active + Opponent active: 2 * MON_FEAT_SIZE = 62
# Tactical: 3
# Agent bench: 5 * BENCH_MON_FEAT_SIZE = 25
# Opponent bench: 5 * OPP_BENCH_MON_FEAT_SIZE = 10
# Party HP fractions: 2 sides * 6 = 12
# Party alive counts: 2 sides * 1 = 2
# Field: weather_onehot(6) + side_status(4: reflect/lightscreen per side)
#   + spikes(2) + turn(1)
FIELD_FEAT_SIZE = 6 + 4 + 2 + 1  # = 13

TOTAL_OBS_SIZE = (
    4 * MOVE_FEAT_SIZE
    + 4 * OPP_MOVE_FEAT_SIZE
    + 2 * MON_FEAT_SIZE
    + TACTICAL_FEAT_SIZE
    + NUM_BENCH_SLOTS * BENCH_MON_FEAT_SIZE
    + NUM_BENCH_SLOTS * OPP_BENCH_MON_FEAT_SIZE
    + 12  # party HP fractions
    + 2   # alive counts
    + FIELD_FEAT_SIZE
)
# = 112 + 36 + 62 + 3 + 25 + 10 + 12 + 2 + 13 = 275


# ---------------------------------------------------------------------------
# Wrapper
# ---------------------------------------------------------------------------


class FeaturizedObsWrapper(gym.Wrapper):
    """Convert raw integer observations into normalised, meaningful features.

    Replaces the Dict observation space with a flat Box of size
    :data:`TOTAL_OBS_SIZE`.  Also strips ``action_mask`` and exposes it
    via ``action_masks()`` for MaskablePPO compatibility.
    """

    def __init__(self, env: gym.Env) -> None:
        super().__init__(env)
        # Pre-load data tables
        _build_type_chart()
        _load_move_db()

        self.observation_space = spaces.Box(
            low=-1.0, high=5.0, shape=(TOTAL_OBS_SIZE,), dtype=np.float32,
        )
        self._last_mask = np.ones(env.action_space.n, dtype=np.uint8)

    # ---- helpers ----

    @staticmethod
    def _stat_stage_mult(stage: int) -> float:
        """Gen 3 stat stage multiplier: stage in [-6, +6]."""
        num = max(2, 2 + stage)
        den = max(2, 2 - stage)
        return num / den

    def _estimate_damage(
        self,
        move_id: int,
        atk_stats: np.ndarray,  # [atk, def, spd, spatk, spdef]
        atk_stages: np.ndarray,  # stat stages array
        atk_level: int,
        atk_types: np.ndarray,  # (2,)
        def_stats: np.ndarray,
        def_stages: np.ndarray,
        def_types: np.ndarray,
        def_max_hp: float,
    ) -> float:
        """Estimate damage as fraction of defender's max HP (0-1+)."""
        if move_id == 0 or def_max_hp <= 0:
            return 0.0
        info = get_move_info(move_id)
        power = info["power"]
        if power == 0:
            return 0.0
        move_type = info["type"]

        # Determine physical/special and get relevant stats
        if move_type in PHYSICAL_TYPES:
            atk_val = float(atk_stats[0]) * self._stat_stage_mult(int(atk_stages[1]))
            def_val = float(def_stats[1]) * self._stat_stage_mult(int(def_stages[2]))
        elif move_type in SPECIAL_TYPES:
            atk_val = float(atk_stats[3]) * self._stat_stage_mult(int(atk_stages[4]))
            def_val = float(def_stats[4]) * self._stat_stage_mult(int(def_stages[5]))
        else:
            return 0.0  # Mystery type

        if def_val <= 0:
            def_val = 1.0

        # Gen 3 damage formula (average random roll = 0.925)
        damage = ((2.0 * atk_level / 5.0 + 2.0) * power * atk_val / def_val) / 50.0 + 2.0
        # STAB
        if move_type == atk_types[0] or move_type == atk_types[1]:
            damage *= 1.5
        # Type effectiveness
        damage *= type_effectiveness(move_type, int(def_types[0]), int(def_types[1]))
        # Average random factor
        damage *= 0.925

        return min(damage / def_max_hp, 5.0)

    @staticmethod
    def _type_onehot(type_id: int) -> np.ndarray:
        oh = np.zeros(NUM_TYPES, dtype=np.float32)
        if 0 <= type_id < NUM_TYPES:
            oh[type_id] = 1.0
        return oh

    @staticmethod
    def _status1_flags(status1: int) -> np.ndarray:
        """Decode status1 bitfield into 6 binary flags."""
        flags = np.zeros(6, dtype=np.float32)
        # Bits: sleep=0-2 (count), poison=3, burn=4, freeze=5, paralyse=6, toxic=7
        if status1 & 0x7:  # sleep (bits 0-2)
            flags[0] = 1.0
        if status1 & (1 << 3):  # poison
            flags[1] = 1.0
        if status1 & (1 << 4):  # burn
            flags[2] = 1.0
        if status1 & (1 << 5):  # freeze
            flags[3] = 1.0
        if status1 & (1 << 6):  # paralyse
            flags[4] = 1.0
        if status1 & (1 << 7):  # toxic
            flags[5] = 1.0
        return flags

    @staticmethod
    def _weather_onehot(weather: int) -> np.ndarray:
        """Encode weather as one-hot (none, rain, sun, sand, hail, other)."""
        oh = np.zeros(6, dtype=np.float32)
        if weather == 0:
            oh[0] = 1.0
        elif weather & 0x7:  # rain
            oh[1] = 1.0
        elif weather & 0x60:  # sun
            oh[2] = 1.0
        elif weather & 0x18:  # sandstorm
            oh[3] = 1.0
        elif weather & 0x80:  # hail
            oh[4] = 1.0
        else:
            oh[5] = 1.0
        return oh

    def _featurize(self, obs: dict[str, np.ndarray]) -> np.ndarray:
        """Convert raw observation dict to flat feature vector."""
        features: list[np.ndarray] = []

        # Determine agent vs opponent battler indices
        # In singles: battler 0 = agent (side 0), battler 1 = opponent (side 1)
        agent_idx = 0
        opp_idx = 1

        agent_types = obs["active_types"][agent_idx]  # (2,)
        opp_types = obs["active_types"][opp_idx]  # (2,)

        # Grab stats/stages for damage estimation
        agent_stats = obs["active_stats"][agent_idx]    # [atk, def, spd, spatk, spdef]
        agent_stages = obs["active_stat_stages"][agent_idx]
        agent_level = int(obs["active_level"][agent_idx])
        opp_stats = obs["active_stats"][opp_idx]
        opp_stages = obs["active_stat_stages"][opp_idx]
        opp_level = int(obs["active_level"][opp_idx])
        opp_max_hp = float(obs["active_max_hp"][opp_idx])
        agent_max_hp = float(obs["active_max_hp"][agent_idx])

        agent_dmg_fracs = []  # for tactical features later
        opp_dmg_fracs = []

        # ---- Agent's 4 moves ----
        for m in range(BATTLE_MAX_MOVES):
            move_id = int(obs["active_moves"][agent_idx, m])
            pp = int(obs["active_pp"][agent_idx, m])
            info = get_move_info(move_id)

            power = info["power"] / 150.0  # normalise (max ~150)
            accuracy = info["accuracy"] / 100.0 if info["accuracy"] > 0 else 1.0
            priority = info["priority"] / 5.0  # range typically -7 to +5
            move_type = info["type"]
            max_pp = info["pp"] if info["pp"] > 0 else 1
            pp_frac = min(pp / max_pp, 1.0) if move_id != 0 else 0.0

            # Category: physical / special / status
            cat = np.zeros(3, dtype=np.float32)
            if info["power"] > 0:
                if move_type in PHYSICAL_TYPES:
                    cat[0] = 1.0
                elif move_type in SPECIAL_TYPES:
                    cat[1] = 1.0
            else:
                cat[2] = 1.0  # status move

            # STAB (same type attack bonus)
            stab = 1.0 if (move_type == agent_types[0] or move_type == agent_types[1]) else 0.0

            # Type effectiveness vs opponent
            eff = type_effectiveness(move_type, int(opp_types[0]), int(opp_types[1]))
            # Normalise: 0x->0, 0.25x->0.125, 0.5x->0.25, 1x->0.5, 2x->1.0, 4x->2.0
            eff_norm = eff / 2.0

            type_oh = self._type_onehot(move_type)

            # Damage estimate (fraction of opponent HP)
            dmg_frac = self._estimate_damage(
                move_id, agent_stats, agent_stages, agent_level,
                agent_types, opp_stats, opp_stages, opp_types, opp_max_hp,
            )
            agent_dmg_fracs.append(dmg_frac)

            move_feat = np.concatenate([
                np.array([power, accuracy, priority], dtype=np.float32),
                type_oh,
                cat,
                np.array([stab, eff_norm, pp_frac, dmg_frac], dtype=np.float32),
            ])
            features.append(move_feat)

        # ---- Opponent's 4 moves (condensed features) ----
        for m in range(BATTLE_MAX_MOVES):
            move_id = int(obs["active_moves"][opp_idx, m])
            info = get_move_info(move_id)

            power = info["power"] / 150.0
            accuracy = info["accuracy"] / 100.0 if info["accuracy"] > 0 else 1.0
            priority = info["priority"] / 5.0
            move_type = info["type"]

            cat = np.zeros(3, dtype=np.float32)
            if info["power"] > 0:
                if move_type in PHYSICAL_TYPES:
                    cat[0] = 1.0
                elif move_type in SPECIAL_TYPES:
                    cat[1] = 1.0
            else:
                cat[2] = 1.0

            stab = 1.0 if (move_type == opp_types[0] or move_type == opp_types[1]) else 0.0
            eff = type_effectiveness(move_type, int(agent_types[0]), int(agent_types[1]))
            eff_norm = eff / 2.0

            # Damage estimate (fraction of agent HP)
            dmg_frac = self._estimate_damage(
                move_id, opp_stats, opp_stages, opp_level,
                opp_types, agent_stats, agent_stages, agent_types, agent_max_hp,
            )
            opp_dmg_fracs.append(dmg_frac)

            opp_move_feat = np.array(
                [power, accuracy, priority, cat[0], cat[1], cat[2], stab, eff_norm, dmg_frac],
                dtype=np.float32,
            )
            features.append(opp_move_feat)

        # ---- Active mon features (agent + opponent) ----
        for idx in [agent_idx, opp_idx]:
            hp = float(obs["active_hp"][idx])
            max_hp = float(obs["active_max_hp"][idx])
            hp_frac = hp / max_hp if max_hp > 0 else 0.0

            types = obs["active_types"][idx]
            type_oh = np.zeros(NUM_TYPES, dtype=np.float32)
            t1, t2 = int(types[0]), int(types[1])
            if 0 <= t1 < NUM_TYPES:
                type_oh[t1] = 1.0
            if 0 <= t2 < NUM_TYPES and t2 != t1:
                type_oh[t2] = 1.0

            # Stat stages: indices 1-5 are atk/def/spd/spatk/spdef (skip hp/acc/eva)
            stages = obs["active_stat_stages"][idx]
            combat_stages = np.array([
                stages[1], stages[2], stages[3], stages[4], stages[5]
            ], dtype=np.float32) / 6.0  # normalise to [-1, 1]

            status_flags = self._status1_flags(int(obs["active_status1"][idx]))
            level = float(obs["active_level"][idx]) / 100.0

            mon_feat = np.concatenate([
                np.array([hp_frac], dtype=np.float32),
                type_oh,
                combat_stages,
                status_flags,
                np.array([level], dtype=np.float32),
            ])
            features.append(mon_feat)

        # ---- Tactical features ----
        # Speed advantage: is agent faster? (accounts for stat stages + paralysis)
        agent_spd = float(agent_stats[2]) * self._stat_stage_mult(int(agent_stages[3]))
        opp_spd = float(opp_stats[2]) * self._stat_stage_mult(int(opp_stages[3]))
        # Paralysis quarters speed
        if int(obs["active_status1"][agent_idx]) & (1 << 6):
            agent_spd *= 0.25
        if int(obs["active_status1"][opp_idx]) & (1 << 6):
            opp_spd *= 0.25
        speed_adv = 1.0 if agent_spd > opp_spd else 0.0

        # Can agent KO opponent this turn? (best move damage > opp current HP frac)
        opp_hp_frac = float(obs["active_hp"][opp_idx]) / opp_max_hp if opp_max_hp > 0 else 0.0
        can_ko = 1.0 if (agent_dmg_fracs and max(agent_dmg_fracs) >= opp_hp_frac > 0) else 0.0

        # Can opponent KO agent this turn?
        agent_hp_frac = float(obs["active_hp"][agent_idx]) / agent_max_hp if agent_max_hp > 0 else 0.0
        opp_can_ko = 1.0 if (opp_dmg_fracs and max(opp_dmg_fracs) >= agent_hp_frac > 0) else 0.0

        features.append(np.array([speed_adv, can_ko, opp_can_ko], dtype=np.float32))

        # ---- Agent bench mon features (contextual switch info) ----
        agent_side = 0
        opp_side = 1
        active_species = int(obs["active_species"][agent_idx])
        active_hp_val = int(obs["active_hp"][agent_idx])

        agent_skipped = False
        agent_bench_feats: list[np.ndarray] = []
        for j in range(BATTLE_PARTY_SIZE):
            pspecies = int(obs["party_species"][agent_side, j])
            php = int(obs["party_hp"][agent_side, j])
            if pspecies == active_species and php == active_hp_val and not agent_skipped:
                agent_skipped = True
                continue
            if pspecies == 0:
                agent_bench_feats.append(np.zeros(BENCH_MON_FEAT_SIZE, dtype=np.float32))
                continue

            pmaxhp = float(obs["party_max_hp"][agent_side, j])
            hp_frac = float(php) / pmaxhp if pmaxhp > 0 else 0.0

            # Defensive type matchup: average effectiveness of opponent's moves vs this mon
            ptypes = obs["party_types"][agent_side, j]  # (2,)
            def_matchup = 0.0
            n_opp_moves = 0
            for m in range(BATTLE_MAX_MOVES):
                omid = int(obs["active_moves"][opp_idx, m])
                if omid == 0:
                    continue
                oinfo = get_move_info(omid)
                if oinfo["power"] > 0:
                    eff = type_effectiveness(oinfo["type"], int(ptypes[0]), int(ptypes[1]))
                    def_matchup += eff
                    n_opp_moves += 1
            # Lower = better defensively; normalise so 0.5 ~ neutral
            def_matchup = (def_matchup / n_opp_moves / 2.0) if n_opp_moves > 0 else 0.5

            # Best move effectiveness of this bench mon vs opponent
            best_eff = 0.0
            pmoves = obs["party_moves"][agent_side, j]  # (4,)
            for m in range(BATTLE_MAX_MOVES):
                mid = int(pmoves[m])
                if mid == 0:
                    continue
                minfo = get_move_info(mid)
                if minfo["power"] > 0:
                    eff = type_effectiveness(minfo["type"], int(opp_types[0]), int(opp_types[1]))
                    if minfo["type"] == ptypes[0] or minfo["type"] == ptypes[1]:
                        eff *= 1.5
                    best_eff = max(best_eff, eff)
            best_eff_norm = best_eff / 2.0

            has_status = 1.0 if int(obs["party_status"][agent_side, j]) != 0 else 0.0
            is_alive = float(obs["party_alive"][agent_side, j])

            agent_bench_feats.append(np.array([hp_frac, def_matchup, best_eff_norm, has_status, is_alive], dtype=np.float32))

        # Pad/trim to exactly NUM_BENCH_SLOTS
        while len(agent_bench_feats) < NUM_BENCH_SLOTS:
            agent_bench_feats.append(np.zeros(BENCH_MON_FEAT_SIZE, dtype=np.float32))
        for bf in agent_bench_feats[:NUM_BENCH_SLOTS]:
            features.append(bf)

        # ---- Opponent bench features ----
        opp_active_species = int(obs["active_species"][opp_idx])
        opp_active_hp_val = int(obs["active_hp"][opp_idx])
        opp_skipped = False
        opp_bench_feats: list[np.ndarray] = []
        for j in range(BATTLE_PARTY_SIZE):
            pspecies = int(obs["party_species"][opp_side, j])
            php = int(obs["party_hp"][opp_side, j])
            if pspecies == opp_active_species and php == opp_active_hp_val and not opp_skipped:
                opp_skipped = True
                continue
            if pspecies == 0:
                opp_bench_feats.append(np.zeros(OPP_BENCH_MON_FEAT_SIZE, dtype=np.float32))
                continue
            pmaxhp = float(obs["party_max_hp"][opp_side, j])
            hp_frac = float(php) / pmaxhp if pmaxhp > 0 else 0.0
            is_alive = float(obs["party_alive"][opp_side, j])
            opp_bench_feats.append(np.array([hp_frac, is_alive], dtype=np.float32))

        # Pad/trim to exactly NUM_BENCH_SLOTS
        while len(opp_bench_feats) < NUM_BENCH_SLOTS:
            opp_bench_feats.append(np.zeros(OPP_BENCH_MON_FEAT_SIZE, dtype=np.float32))
        for bf in opp_bench_feats[:NUM_BENCH_SLOTS]:
            features.append(bf)

        # ---- Party HP fractions (both sides) ----
        for side in range(BATTLE_NUM_SIDES):
            for j in range(BATTLE_PARTY_SIZE):
                hp = float(obs["party_hp"][side, j])
                max_hp = float(obs["party_max_hp"][side, j])
                features.append(np.array([hp / max_hp if max_hp > 0 else 0.0], dtype=np.float32))

        # ---- Alive counts per side (normalised by 6) ----
        for side in range(BATTLE_NUM_SIDES):
            alive = sum(int(obs["party_alive"][side, j]) for j in range(BATTLE_PARTY_SIZE))
            features.append(np.array([alive / 6.0], dtype=np.float32))

        # ---- Field features ----
        weather_oh = self._weather_onehot(int(obs["weather"][0]))
        features.append(weather_oh)

        # Side status flags (Reflect=bit1, Light Screen=bit2 per side)
        for side in range(BATTLE_NUM_SIDES):
            ss = int(obs["side_status"][side])
            features.append(np.array([
                float(bool(ss & 0x1)),   # Reflect
                float(bool(ss & 0x2)),   # Light Screen
            ], dtype=np.float32))

        # Spikes per side (normalised by 3)
        for side in range(BATTLE_NUM_SIDES):
            features.append(np.array([float(obs["spikes"][side]) / 3.0], dtype=np.float32))

        # Turn (normalised)
        features.append(np.array([float(obs["turn"][0]) / 200.0], dtype=np.float32))

        return np.concatenate(features)

    # ---- gym.Wrapper overrides ----

    def _extract_mask(self, obs: dict, info: dict) -> np.ndarray:
        """Find action_mask in obs dict or info dict."""
        if "action_mask" in obs:
            return obs["action_mask"]
        if "action_mask" in info:
            return info["action_mask"]
        return np.ones(self.env.action_space.n, dtype=np.uint8)

    def reset(self, **kwargs: Any) -> tuple[np.ndarray, dict[str, Any]]:
        obs, info = self.env.reset(**kwargs)
        self._last_mask = self._extract_mask(obs, info)
        feat = self._featurize(obs)
        info["action_mask"] = self._last_mask
        return feat, info

    def step(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        obs, reward, terminated, truncated, info = self.env.step(action)
        self._last_mask = self._extract_mask(obs, info)
        feat = self._featurize(obs)
        info["action_mask"] = self._last_mask
        return feat, reward, terminated, truncated, info

    def action_masks(self) -> np.ndarray:
        """Return the current action mask (called by ``MaskablePPO``)."""
        return self._last_mask
